name: esea_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Networking
  dio: ^5.4.0

  # Local Storage
  shared_preferences: ^2.2.2

  # UI Components
  cached_network_image: ^3.3.0
  qr_flutter: ^4.1.0
  shimmer: ^3.0.0

  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.2

  # Icons
  cupertino_icons: ^1.0.6

  flutter_secure_storage: ^9.2.2
  app_links: ^7.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/esea_logo.png
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
